packages:
  - apps/*
  - packages/*
  - packages/hmeqo/*
allowBuilds:
  "@parcel/watcher": true
  "@varlet/nuxt": true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
overrides:
  vite: npm:rolldown-vite@latest
publicHoistPattern:
  - "*"
