/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum - version 0.2.0
 *
 * Utoipa&#x27;s axum bindings for seamless integration for the two
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.index': ['GET', '/api'],
  'auth.login': ['POST', '/api/auth/login'],
  'auth.logout': ['POST', '/api/auth/logout'],
  'auth.me': ['GET', '/api/auth/me'],
  'general.hello': ['POST', '/api/hello'],
  'user.list': ['GET', '/api/users'],
  'user.create': ['POST', '/api/users'],
  'user.get': ['GET', '/api/users/{id}'],
  'user.delete_': ['DELETE', '/api/users/{id}'],
  'user.change_password': ['PUT', '/api/users/{id}/password'],
  'user.update_username': ['PUT', '/api/users/{id}/username']
};
