/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum - version 0.2.0
 *
 * Utoipa&#x27;s axum bindings for seamless integration for the two
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type I64 = number;
export interface LoginRequest {
  password: string;
  username: string;
}
export interface HelloRequest {
  name: string;
}
export interface CreateUserRequest {
  password: string;
  username: string;
}
export interface MessageResponse {
  message: string;
}
export interface UserResponse {
  created_at: string;
  id: I64;
  updated_at: string;
  username: string;
}
export interface AuthStateResponse {
  user: UserResponse;
}
export interface ChangePasswordRequest {
  new_password: string;
  old_password: string;
}
export interface UpdateUsernameRequest {
  username: string;
}
export interface LoginResponse {
  state: AuthStateResponse;
}
export interface HelloResponse {
  message: string;
}
export interface UserListResponse {
  page: number;
  per_page: number;
  total: number;
  users: UserResponse[];
}
declare global {
  interface Apis {
    general: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      index<Config extends Alova2MethodConfig<unknown>>(
        config?: Config
      ): Alova2Method<unknown, 'general.index', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/hello
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      hello<
        Config extends Alova2MethodConfig<HelloResponse> & {
          data: HelloRequest;
        }
      >(
        config: Config
      ): Alova2Method<HelloResponse, 'general.hello', Config>;
    };
    auth: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   state: {
       *     user: {
       *       created_at: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }
       *   }
       * }
       * ```
       */
      login<
        Config extends Alova2MethodConfig<LoginResponse> & {
          data: LoginRequest;
        }
      >(
        config: Config
      ): Alova2Method<LoginResponse, 'auth.login', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      logout<Config extends Alova2MethodConfig<MessageResponse>>(
        config?: Config
      ): Alova2Method<MessageResponse, 'auth.logout', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/auth/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   user: {
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       * }
       * ```
       */
      me<Config extends Alova2MethodConfig<AuthStateResponse>>(
        config?: Config
      ): Alova2Method<AuthStateResponse, 'auth.me', Config>;
    };
    user: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/users
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // Page number
       *   page?: number
       *   // Items per page
       *   per_page?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   page: number
       *   per_page: number
       *   total: number
       *   // [items] start
       *   // [items] end
       *   users: Array<{
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }>
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<UserListResponse> & {
          params: {
            /**
             * Page number
             */
            page?: number;
            /**
             * Items per page
             */
            per_page?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserListResponse, 'user.list', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<UserResponse> & {
          data: CreateUserRequest;
        }
      >(
        config: Config
      ): Alova2Method<UserResponse, 'user.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<UserResponse> & {
          pathParams: {
            id: I64;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserResponse, 'user.get', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      delete_<
        Config extends Alova2MethodConfig<MessageResponse> & {
          pathParams: {
            id: I64;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResponse, 'user.delete_', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/users/{id}/password
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   new_password: string
       *   old_password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      change_password<
        Config extends Alova2MethodConfig<MessageResponse> & {
          pathParams: {
            id: I64;
          };
          data: ChangePasswordRequest;
        }
      >(
        config: Config
      ): Alova2Method<MessageResponse, 'user.change_password', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/users/{id}/username
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      update_username<
        Config extends Alova2MethodConfig<UserResponse> & {
          pathParams: {
            id: I64;
          };
          data: UpdateUsernameRequest;
        }
      >(
        config: Config
      ): Alova2Method<UserResponse, 'user.update_username', Config>;
    };
  }

  var Apis: Apis;
}
