/* tslint:disable */
/* eslint-disable */
/**
 * utoipa-axum - version 0.2.0
 *
 * Utoipa&#x27;s axum bindings for seamless integration for the two
 *
 * OpenAPI version: 3.1.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export type I64 = number;
export interface LoginReq {
  password: string;
  username: string;
}
export interface RefreshReq {
  refresh_token: string;
}
export interface HelloReq {
  name: string;
}
export interface CreateUserReq {
  password: string;
  username: string;
}
export type Perm =
  | '*'
  | 'user:read'
  | 'user:write'
  | 'user:delete'
  | 'user:*'
  | 'role:read'
  | 'role:write'
  | 'role:delete'
  | 'role:*';
export interface UserResp {
  created_at: string;
  id: I64;
  updated_at: string;
  username: string;
}
export interface AuthStateResp {
  permissions: Perm[];
  user: UserResp;
}
export interface ErrorResp {
  code: string;
  detail?: string | null;
  errors?: object;
}
export interface ChangePasswordReq {
  new_password: string;
  old_password: string;
}
export interface UpdateUsernameReq {
  username: string;
}
export interface LoginResp {
  access_token: string;
  refresh_token: string;
  state: AuthStateResp;
}
export interface RefreshResp {
  access_token: string;
  refresh_token: string;
}
export interface HelloResp {
  message: string;
}
export interface UserListResp {
  page: number;
  per_page: number;
  total: number;
  users: UserResp[];
}
export interface MessageResp {
  message: string;
}
declare global {
  interface Apis {
    chore: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = unknown
       * ```
       */
      index<Config extends Alova2MethodConfig<unknown>>(config?: Config): Alova2Method<unknown, 'chore.index', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/error
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   code: string
       *   detail?: string | null
       *   errors?: object
       * }
       * ```
       */
      error<Config extends Alova2MethodConfig<ErrorResp>>(
        config?: Config
      ): Alova2Method<ErrorResp, 'chore.error', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/hello
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   name: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      hello<
        Config extends Alova2MethodConfig<HelloResp> & {
          data: HelloReq;
        }
      >(
        config: Config
      ): Alova2Method<HelloResp, 'chore.hello', Config>;
    };
    jwtDemo: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/auth/jwt/echo
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      echo<Config extends Alova2MethodConfig<null>>(config?: Config): Alova2Method<null, 'jwtDemo.echo', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/jwt/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   access_token: string
       *   refresh_token: string
       *   state: {
       *     // [items] start
       *     // [items] end
       *     permissions: (
       *       | '*'
       *       | 'user:read'
       *       | 'user:write'
       *       | 'user:delete'
       *       | 'user:*'
       *       | 'role:read'
       *       | 'role:write'
       *       | 'role:delete'
       *       | 'role:*'
       *     )[]
       *     user: {
       *       created_at: string
       *       id: number
       *       updated_at: string
       *       username: string
       *     }
       *   }
       * }
       * ```
       */
      login<
        Config extends Alova2MethodConfig<LoginResp> & {
          data: LoginReq;
        }
      >(
        config: Config
      ): Alova2Method<LoginResp, 'jwtDemo.login', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/jwt/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      logout<Config extends Alova2MethodConfig<null>>(config?: Config): Alova2Method<null, 'jwtDemo.logout', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/auth/jwt/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   permissions: (
       *     | '*'
       *     | 'user:read'
       *     | 'user:write'
       *     | 'user:delete'
       *     | 'user:*'
       *     | 'role:read'
       *     | 'role:write'
       *     | 'role:delete'
       *     | 'role:*'
       *   )[]
       *   user: {
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       * }
       * ```
       */
      me<Config extends Alova2MethodConfig<AuthStateResp>>(
        config?: Config
      ): Alova2Method<AuthStateResp, 'jwtDemo.me', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/jwt/refresh
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   refresh_token: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   access_token: string
       *   refresh_token: string
       * }
       * ```
       */
      refresh<
        Config extends Alova2MethodConfig<RefreshResp> & {
          data: RefreshReq;
        }
      >(
        config: Config
      ): Alova2Method<RefreshResp, 'jwtDemo.refresh', Config>;
    };
    auth: {
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/login
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   permissions: (
       *     | '*'
       *     | 'user:read'
       *     | 'user:write'
       *     | 'user:delete'
       *     | 'user:*'
       *     | 'role:read'
       *     | 'role:write'
       *     | 'role:delete'
       *     | 'role:*'
       *   )[]
       *   user: {
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       * }
       * ```
       */
      login<
        Config extends Alova2MethodConfig<AuthStateResp> & {
          data: LoginReq;
        }
      >(
        config: Config
      ): Alova2Method<AuthStateResp, 'auth.login', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/auth/logout
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = null
       * ```
       */
      logout<Config extends Alova2MethodConfig<null>>(config?: Config): Alova2Method<null, 'auth.logout', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/auth/me
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // [items] start
       *   // [items] end
       *   permissions: (
       *     | '*'
       *     | 'user:read'
       *     | 'user:write'
       *     | 'user:delete'
       *     | 'user:*'
       *     | 'role:read'
       *     | 'role:write'
       *     | 'role:delete'
       *     | 'role:*'
       *   )[]
       *   user: {
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }
       * }
       * ```
       */
      me<Config extends Alova2MethodConfig<AuthStateResp>>(
        config?: Config
      ): Alova2Method<AuthStateResp, 'auth.me', Config>;
    };
    user: {
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/users
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   // Page number
       *   page?: number
       *   // Items per page
       *   per_page?: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   page: number
       *   per_page: number
       *   total: number
       *   // [items] start
       *   // [items] end
       *   users: Array<{
       *     created_at: string
       *     id: number
       *     updated_at: string
       *     username: string
       *   }>
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<UserListResp> & {
          params: {
            /**
             * Page number
             */
            page?: number;
            /**
             * Items per page
             */
            per_page?: number;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserListResp, 'user.list', Config>;
      /**
       * ---
       *
       * [POST]
       *
       * **path:** /api/users
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      create<
        Config extends Alova2MethodConfig<UserResp> & {
          data: CreateUserReq;
        }
      >(
        config: Config
      ): Alova2Method<UserResp, 'user.create', Config>;
      /**
       * ---
       *
       * [GET]
       *
       * **path:** /api/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      get<
        Config extends Alova2MethodConfig<UserResp> & {
          pathParams: {
            id: I64;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserResp, 'user.get', Config>;
      /**
       * ---
       *
       * [DELETE]
       *
       * **path:** /api/users/{id}
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      delete_<
        Config extends Alova2MethodConfig<MessageResp> & {
          pathParams: {
            id: I64;
          };
        }
      >(
        config: Config
      ): Alova2Method<MessageResp, 'user.delete_', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/users/{id}/password
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   new_password: string
       *   old_password: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   message: string
       * }
       * ```
       */
      change_password<
        Config extends Alova2MethodConfig<MessageResp> & {
          pathParams: {
            id: I64;
          };
          data: ChangePasswordReq;
        }
      >(
        config: Config
      ): Alova2Method<MessageResp, 'user.change_password', Config>;
      /**
       * ---
       *
       * [PUT]
       *
       * **path:** /api/users/{id}/username
       *
       * ---
       *
       * **Path Parameters**
       * ```ts
       * type PathParameters = {
       *   id: number
       * }
       * ```
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   created_at: string
       *   id: number
       *   updated_at: string
       *   username: string
       * }
       * ```
       */
      update_username<
        Config extends Alova2MethodConfig<UserResp> & {
          pathParams: {
            id: I64;
          };
          data: UpdateUsernameReq;
        }
      >(
        config: Config
      ): Alova2Method<UserResp, 'user.update_username', Config>;
    };
  }

  var Apis: Apis;
}
